### ISSUE TITLE
Hotkey support?

### ISSUE THREAD

**Issue by Freed-Wu** [jeffwright13/pytest-tui#72]
It looks like pytest-tui only have a hotkey `Q` (quit). Does there exist more hotkeys (like readline or vim) or any customization method? Does there exist any hotkey which can open the test failed file?  Thanks.

**Comment by jeffwright13** [comment]
Thank you for the feedback. You are the second person to request this. It's literally Issue #1 in this repo :-)  https://github.com/jeffwright13/pytest-tui/issues/1. 

Hotkeys can be handled in Textual (which is the TUI framework here). I have not thought a lot about this lately, because I don't really use the TUI in this way (I am more a keyboard/mouse guy); but it should be mostly a matter of deciding which keys to support, and what their key assignments are. I'll give it some more thought, an din the meantime, if you have a list of top 10 keystrokes you'd like to see implemented, let me know.

**Comment by Freed-Wu** [comment]
Oh, this issue is a repetition of #1. Close.
